from django.urls import reverse
from rest_framework.test import APITestCase, APIClient
from django.contrib.auth import get_user_model
from rest_framework_simplejwt.tokens import RefreshToken
from ..models import Order, Customer  

User = get_user_model()

class OrderAuthTests(APITestCase):
    def setUp(self):
        self.client = APIClient()

        # Create a demo user
        self.user = User.objects.create_user(
            username="oliver",
            email="oliver@example.com",
            password="testpass123"
        )

        # Issue JWT for that user
        refresh = RefreshToken.for_user(self.user)
        self.access = str(refresh.access_token)

        # Create a test customer
        self.customer = Customer.objects.create(
            name="Oliver Mutuku", 
            code="C001"
        )

        # Create a test order
        self.order = Order.objects.create(
            customer=self.customer,
            item="Laptop", 
            amount=1200
        )

    def test_orders_requires_authentication(self):
        url = reverse("order-list")  # generated by DefaultRouter
        response = self.client.get(url)
        self.assertEqual(response.status_code, 401)

    def test_orders_with_token_returns_data(self):
        url = reverse("order-list")
        response = self.client.get(
            url, 
            HTTP_AUTHORIZATION=f"Bearer {self.access}"
        )
        self.assertEqual(response.status_code, 200)
        self.assertGreaterEqual(len(response.data), 1)
        self.assertEqual(response.data[0]["item"], "Laptop")
